mode: debug #启动模式 debug, release
port: :8080 #启动端口
app-name: apiserver-gin #服务名称
url: http://localhost #服务本地地址
max-ping-count: 10 #自检次数
jwt-secret: 
#language: zh # 项目语言，en或者zh
# 数据库配置（mysql）
database:
  dbname: #数据库名称
  host: 127.0.0.1 #数据库服务地址
  port:  #数据库端口
  username:  #用户名(实际线上不可使用root,请授权一个账户)
  password:  #密码
  maximum-pool-size: 50  #连接池最大连接数
  maximum-idle-size: 10  #连接池最大空闲数

# 日志配置(使用zap&lumberjack)
log:
  level: debug
  time-format: '2006-01-02 15:04:05.000'
  max-size: 500 #单个日志文件大小MB
  max-backups: 7 #至多保留多少个日志文件
  max-age: 7 #至多保留多少天的日志文件
  compress: true
  local-time: false
  console: true  #是否打印到控制台,true打印到控制台，false记录到文件